//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Scripts/Units/Player/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""e85b5aaf-ef78-46ee-b6ca-7f5b957e9385"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""1c2b364e-61f6-4852-b2d5-602a1d30ee1c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ec8d6230-a10c-4f7b-85ff-05b26830e5a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""e2f608f4-f665-4e0f-8888-bc5af12268c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""41d60d54-6d52-4a7a-b998-f2da549e0659"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAttack"",
                    ""type"": ""Button"",
                    ""id"": ""f924c3fc-1c72-46e0-8318-e7a765ee0441"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAttack"",
                    ""type"": ""Button"",
                    ""id"": ""51e7778c-8b2d-4a8c-92e8-f7875616afa0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""83dbfbed-b9fa-44e0-99d9-c58cd49a6c62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterMenu"",
                    ""type"": ""Button"",
                    ""id"": ""ed4ae36e-3f45-4f3a-b10f-e1aa02fb6db1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CraftMenu"",
                    ""type"": ""Button"",
                    ""id"": ""624ad7b4-2a11-4bb8-a3df-bcd361192feb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionsMenu"",
                    ""type"": ""Button"",
                    ""id"": ""3c082585-6d47-4fbd-aafb-5093e8875b2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAmmo"",
                    ""type"": ""Button"",
                    ""id"": ""24673f08-8e38-400a-8b46-107a692051df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Potion_1"",
                    ""type"": ""Button"",
                    ""id"": ""dd8b9c55-494b-4bce-8c95-984dbe080480"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Potion_2"",
                    ""type"": ""Button"",
                    ""id"": ""b362e828-5b2a-4017-b15e-c31685f3659d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Potion_3"",
                    ""type"": ""Button"",
                    ""id"": ""9e0ea9e0-3950-4ac4-8cb3-ae43b78fd861"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Potion_4"",
                    ""type"": ""Button"",
                    ""id"": ""283802ec-8256-4f1f-8a15-010c640ecef2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1743cb72-4e11-4bf1-8b09-8cd8b824cac7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""70e1157e-85c6-4996-817b-3681080849f5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0084823d-e4b3-4ec2-811b-fa76160e2a37"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""63f577e6-bf5c-4c2d-a429-1f8061155489"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ab981a4e-f2be-46c9-9276-3d3dfed44ee8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d7a98d4d-0c88-4a63-8f09-4c273260c85d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5dac805-b00e-43d9-b51e-6cac5d79cd24"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35970cb7-28cd-4238-aa0c-1d72c3489d74"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e935ff-7850-4276-8b3f-3728aa87af2a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57529c01-e2f2-4cf2-9988-30b945c70369"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""SlowTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e86a67c-c66e-457c-aaf1-10d3325f4a78"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""888fcce8-ae06-4a19-a19d-c00dc543e84f"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a6049bd-b30e-4558-af62-b4f3ab95f0d8"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CraftMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a21063c-5cae-415d-be45-56fe863ce7e3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1778ed9e-afb9-4f84-83c4-0b52b4ef3030"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAmmo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdd03eaf-70ce-477e-b15e-69e6cf2e8608"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Potion_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97df37c4-4ec3-485c-b9ff-251bb64dedd1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Potion_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6667087-2a2a-4bf8-b932-791c2c0cf6ab"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Potion_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bc996f0-e797-4cab-8533-d2e0fae2f159"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Potion_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""24141f66-5a1a-435b-9ba2-648d7c3d5ec5"",
            ""actions"": [
                {
                    ""name"": ""CloseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""e0aab4e6-a9d5-4b28-9428-3e90bc15810b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CharacterMenu"",
                    ""type"": ""Button"",
                    ""id"": ""0dd548a8-9568-4e60-806e-f63ba6486708"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CraftMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4a586b8f-d7ac-4807-918b-fd5e27ace154"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionMenu"",
                    ""type"": ""Button"",
                    ""id"": ""06ae4896-3103-4ef9-ac24-1e39b5f09f38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9016cd71-d532-4303-91ec-11b448e6c948"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f598326d-5e9a-4855-ad0c-ed6fe95a5dcd"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CharacterMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""362b507a-10ba-43d3-bf67-46dbd9e1482c"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CraftMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8ac0f78-d1f9-473c-b4c8-e1c7b80fbbef"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""26a6a92f-73b1-492a-b222-4c5773c02bec"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
        m_Gameplay_Interact = m_Gameplay.FindAction("Interact", throwIfNotFound: true);
        m_Gameplay_Roll = m_Gameplay.FindAction("Roll", throwIfNotFound: true);
        m_Gameplay_PrimaryAttack = m_Gameplay.FindAction("PrimaryAttack", throwIfNotFound: true);
        m_Gameplay_SecondaryAttack = m_Gameplay.FindAction("SecondaryAttack", throwIfNotFound: true);
        m_Gameplay_ChangeWeapon = m_Gameplay.FindAction("ChangeWeapon", throwIfNotFound: true);
        m_Gameplay_CharacterMenu = m_Gameplay.FindAction("CharacterMenu", throwIfNotFound: true);
        m_Gameplay_CraftMenu = m_Gameplay.FindAction("CraftMenu", throwIfNotFound: true);
        m_Gameplay_OptionsMenu = m_Gameplay.FindAction("OptionsMenu", throwIfNotFound: true);
        m_Gameplay_SwitchAmmo = m_Gameplay.FindAction("SwitchAmmo", throwIfNotFound: true);
        m_Gameplay_Potion_1 = m_Gameplay.FindAction("Potion_1", throwIfNotFound: true);
        m_Gameplay_Potion_2 = m_Gameplay.FindAction("Potion_2", throwIfNotFound: true);
        m_Gameplay_Potion_3 = m_Gameplay.FindAction("Potion_3", throwIfNotFound: true);
        m_Gameplay_Potion_4 = m_Gameplay.FindAction("Potion_4", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_CloseMenu = m_UI.FindAction("CloseMenu", throwIfNotFound: true);
        m_UI_CharacterMenu = m_UI.FindAction("CharacterMenu", throwIfNotFound: true);
        m_UI_CraftMenu = m_UI.FindAction("CraftMenu", throwIfNotFound: true);
        m_UI_OptionMenu = m_UI.FindAction("OptionMenu", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jump;
    private readonly InputAction m_Gameplay_Interact;
    private readonly InputAction m_Gameplay_Roll;
    private readonly InputAction m_Gameplay_PrimaryAttack;
    private readonly InputAction m_Gameplay_SecondaryAttack;
    private readonly InputAction m_Gameplay_ChangeWeapon;
    private readonly InputAction m_Gameplay_CharacterMenu;
    private readonly InputAction m_Gameplay_CraftMenu;
    private readonly InputAction m_Gameplay_OptionsMenu;
    private readonly InputAction m_Gameplay_SwitchAmmo;
    private readonly InputAction m_Gameplay_Potion_1;
    private readonly InputAction m_Gameplay_Potion_2;
    private readonly InputAction m_Gameplay_Potion_3;
    private readonly InputAction m_Gameplay_Potion_4;
    public struct GameplayActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameplayActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
        public InputAction @Interact => m_Wrapper.m_Gameplay_Interact;
        public InputAction @Roll => m_Wrapper.m_Gameplay_Roll;
        public InputAction @PrimaryAttack => m_Wrapper.m_Gameplay_PrimaryAttack;
        public InputAction @SecondaryAttack => m_Wrapper.m_Gameplay_SecondaryAttack;
        public InputAction @ChangeWeapon => m_Wrapper.m_Gameplay_ChangeWeapon;
        public InputAction @CharacterMenu => m_Wrapper.m_Gameplay_CharacterMenu;
        public InputAction @CraftMenu => m_Wrapper.m_Gameplay_CraftMenu;
        public InputAction @OptionsMenu => m_Wrapper.m_Gameplay_OptionsMenu;
        public InputAction @SwitchAmmo => m_Wrapper.m_Gameplay_SwitchAmmo;
        public InputAction @Potion_1 => m_Wrapper.m_Gameplay_Potion_1;
        public InputAction @Potion_2 => m_Wrapper.m_Gameplay_Potion_2;
        public InputAction @Potion_3 => m_Wrapper.m_Gameplay_Potion_3;
        public InputAction @Potion_4 => m_Wrapper.m_Gameplay_Potion_4;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Interact.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnInteract;
                @Roll.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRoll;
                @PrimaryAttack.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryAttack;
                @PrimaryAttack.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryAttack;
                @PrimaryAttack.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPrimaryAttack;
                @SecondaryAttack.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAttack;
                @SecondaryAttack.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAttack;
                @SecondaryAttack.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAttack;
                @ChangeWeapon.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeWeapon;
                @ChangeWeapon.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeWeapon;
                @CharacterMenu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCharacterMenu;
                @CharacterMenu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCharacterMenu;
                @CharacterMenu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCharacterMenu;
                @CraftMenu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCraftMenu;
                @CraftMenu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCraftMenu;
                @CraftMenu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCraftMenu;
                @OptionsMenu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOptionsMenu;
                @OptionsMenu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOptionsMenu;
                @OptionsMenu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnOptionsMenu;
                @SwitchAmmo.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchAmmo;
                @SwitchAmmo.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchAmmo;
                @SwitchAmmo.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchAmmo;
                @Potion_1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_1;
                @Potion_1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_1;
                @Potion_1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_1;
                @Potion_2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_2;
                @Potion_2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_2;
                @Potion_2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_2;
                @Potion_3.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_3;
                @Potion_3.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_3;
                @Potion_3.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_3;
                @Potion_4.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_4;
                @Potion_4.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_4;
                @Potion_4.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPotion_4;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @PrimaryAttack.started += instance.OnPrimaryAttack;
                @PrimaryAttack.performed += instance.OnPrimaryAttack;
                @PrimaryAttack.canceled += instance.OnPrimaryAttack;
                @SecondaryAttack.started += instance.OnSecondaryAttack;
                @SecondaryAttack.performed += instance.OnSecondaryAttack;
                @SecondaryAttack.canceled += instance.OnSecondaryAttack;
                @ChangeWeapon.started += instance.OnChangeWeapon;
                @ChangeWeapon.performed += instance.OnChangeWeapon;
                @ChangeWeapon.canceled += instance.OnChangeWeapon;
                @CharacterMenu.started += instance.OnCharacterMenu;
                @CharacterMenu.performed += instance.OnCharacterMenu;
                @CharacterMenu.canceled += instance.OnCharacterMenu;
                @CraftMenu.started += instance.OnCraftMenu;
                @CraftMenu.performed += instance.OnCraftMenu;
                @CraftMenu.canceled += instance.OnCraftMenu;
                @OptionsMenu.started += instance.OnOptionsMenu;
                @OptionsMenu.performed += instance.OnOptionsMenu;
                @OptionsMenu.canceled += instance.OnOptionsMenu;
                @SwitchAmmo.started += instance.OnSwitchAmmo;
                @SwitchAmmo.performed += instance.OnSwitchAmmo;
                @SwitchAmmo.canceled += instance.OnSwitchAmmo;
                @Potion_1.started += instance.OnPotion_1;
                @Potion_1.performed += instance.OnPotion_1;
                @Potion_1.canceled += instance.OnPotion_1;
                @Potion_2.started += instance.OnPotion_2;
                @Potion_2.performed += instance.OnPotion_2;
                @Potion_2.canceled += instance.OnPotion_2;
                @Potion_3.started += instance.OnPotion_3;
                @Potion_3.performed += instance.OnPotion_3;
                @Potion_3.canceled += instance.OnPotion_3;
                @Potion_4.started += instance.OnPotion_4;
                @Potion_4.performed += instance.OnPotion_4;
                @Potion_4.canceled += instance.OnPotion_4;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_CloseMenu;
    private readonly InputAction m_UI_CharacterMenu;
    private readonly InputAction m_UI_CraftMenu;
    private readonly InputAction m_UI_OptionMenu;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseMenu => m_Wrapper.m_UI_CloseMenu;
        public InputAction @CharacterMenu => m_Wrapper.m_UI_CharacterMenu;
        public InputAction @CraftMenu => m_Wrapper.m_UI_CraftMenu;
        public InputAction @OptionMenu => m_Wrapper.m_UI_OptionMenu;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @CloseMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCloseMenu;
                @CloseMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCloseMenu;
                @CharacterMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCharacterMenu;
                @CharacterMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCharacterMenu;
                @CharacterMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCharacterMenu;
                @CraftMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCraftMenu;
                @CraftMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCraftMenu;
                @CraftMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCraftMenu;
                @OptionMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnOptionMenu;
                @OptionMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnOptionMenu;
                @OptionMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnOptionMenu;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseMenu.started += instance.OnCloseMenu;
                @CloseMenu.performed += instance.OnCloseMenu;
                @CloseMenu.canceled += instance.OnCloseMenu;
                @CharacterMenu.started += instance.OnCharacterMenu;
                @CharacterMenu.performed += instance.OnCharacterMenu;
                @CharacterMenu.canceled += instance.OnCharacterMenu;
                @CraftMenu.started += instance.OnCraftMenu;
                @CraftMenu.performed += instance.OnCraftMenu;
                @CraftMenu.canceled += instance.OnCraftMenu;
                @OptionMenu.started += instance.OnOptionMenu;
                @OptionMenu.performed += instance.OnOptionMenu;
                @OptionMenu.canceled += instance.OnOptionMenu;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private IMainMenuActions m_MainMenuActionsCallbackInterface;
    public struct MainMenuActions
    {
        private @PlayerInputActions m_Wrapper;
        public MainMenuActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
            {
            }
            m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
            }
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnPrimaryAttack(InputAction.CallbackContext context);
        void OnSecondaryAttack(InputAction.CallbackContext context);
        void OnChangeWeapon(InputAction.CallbackContext context);
        void OnCharacterMenu(InputAction.CallbackContext context);
        void OnCraftMenu(InputAction.CallbackContext context);
        void OnOptionsMenu(InputAction.CallbackContext context);
        void OnSwitchAmmo(InputAction.CallbackContext context);
        void OnPotion_1(InputAction.CallbackContext context);
        void OnPotion_2(InputAction.CallbackContext context);
        void OnPotion_3(InputAction.CallbackContext context);
        void OnPotion_4(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnCloseMenu(InputAction.CallbackContext context);
        void OnCharacterMenu(InputAction.CallbackContext context);
        void OnCraftMenu(InputAction.CallbackContext context);
        void OnOptionMenu(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
    }
}
